### ISSUE TITLE
Milestone 1: Project Setup & Planning

### ISSUE THREAD

**Issue by mivige** [mivige/TotCloudApp#2]
### Milestone 1: Project Setup & Planning
- [x] Create GitHub repository
- [x] Set up development environment
  - [x] Configure Apache server
  - [x] Install MySQL
  - [x] Set up PHP development environment
- [x] Define database schema
- [x] Create API documentation template
- [x] Set up project documentation structure
